

services:
  testmongo:
    image: testmongo
    ports:
      - '45556:443'
    build:
      context: .
      dockerfile: testMongo/Dockerfile
    depends_on:
      - mongodb
    # environment:
    #    - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017
    # environment:
    #   - MONGO_DB_HOST=mongodb
    #   - MONGO_DB_PORT=27018
    #   - MONGO_DB_DATABASE=salles
   
  mongodb:
    image: mongo:6
    container_name: mongoDb
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_DATABASE: salles
    volumes:
      - dbdata6:/data/db
      - ./testMongo/init-scripts/:/docker-entrypoint-initdb.d/
volumes:
  dbdata6:
